# Generated by Django 3.1.4 on 2020-12-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201215_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palestra',
            old_name='palestrante',
            new_name='nome',
        ),
    ]
