# Generated by Django 3.1.4 on 2020-12-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201216_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestra',
            name='hora',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
