# Generated by Django 3.1.4 on 2020-12-16 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201216_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palestra',
            name='hora',
        ),
    ]
