# Generated by Django 3.1.4 on 2020-12-16 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_palestra_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestra',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
